name: Unit Tests

on:
  push:
    branches:
      - main  # Adjust this branch name if necessary
  pull_request:
    branches:
      - main  # Adjust this branch name if necessary

jobs:
  test:
    runs-on: ubuntu-latest  # You can choose a different operating system if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Adjust the Python version if needed


      - name: Run unit tests
        run: python -m unittest discover -s tests -p "test_*.py"
