name: Run tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11


    - name: Install dependencies
      run: |
        pip install sqlalchemy pandas numpy

    - name: Run tests
      run: |
        echo "Executing pipeline.py"
        #python .data/pipeline.py

        # Validate the output file MunsterAutoScout24.db
        #if [ -f "./data/MunsterAutoScout24.db" ]; then
        #  echo "MunsterAutoScout24.db file exists "
        #else
        #  echo "MunsterAutoScout24.db file not found"
        #fi
        echo " Running Test Cases "
        #python ./data/test_pipeline.py